[DP-304] Create overall page layout on dashboard
reustleco/dojo-frontend-app-learner-portal pull request #30
Opened 2022-08-23 12:50 UTC by darjanin

https://woven-dojo.atlassian.net/browse/DP-304

## Changes

  - Create `DashboardPanel` component
  - Show Catalog results on the Dashboard
  - Add empty state component for empty Learning path
  - Simplify the search

## PR checks

* [x] Have you included the task ID in the PR title? (Format: `[ABC-###] - PR title`)
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Does your submission pass them?
* [ ] Have you lint your code locally prior to submission?
* [x] Have you added an explanation of what your changes do?

2022-08-23 14:55 UTC, Alain1405 reviewed
Looks good to me, just one minor comment but @bartosz-szczecinski-gft 's review will be required before merging.

2022-08-23 14:55 UTC, Alain1405 commented on src/components/dashboard/styles/_Dashboard.scss
> +    border-radius: 0.25rem;
I'm assuming the design has the same radiuses everywhere but I am seeing that here it is defined in `rem` while on https://github.com/reustleco/dojo-frontend-common/pull/14 it's on pixel.
On https://github.com/reustleco/dojo-frontend-common/pull/14 we are already working to move the definition of that variable on the brand package. 
Is my assumption correct? If so, @tetianabrzezinska and @darjanin please agree on a unit for this value

2022-08-24 06:31 UTC, bartosz-szczecinski-gft requested changes

2022-08-24 06:31 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +  const renderAvailableCourses = useCallback((count) => (
I think `useMemo` would be more suitable here (though the end result is the same, it's more semantically correct)

2022-08-24 06:31 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/styles/_Dashboard.scss
> +    border-radius: 0.25rem;
Yes, let's finalize the updates to `dojo-brand-admin` and later on use the SCSS variable here, for now we can go with the value being set locally until we release the new version of `dojo-admin-brand` with the border-radius added to https://github.com/reustleco/dojo-admin-brand/blob/d2b2db36c76bdaa6e6d4a9327d602247441f3ae2/paragon/_variables.scss

2022-08-24 06:31 UTC, bartosz-szczecinski-gft commented on src/index.scss
> +// TODO: Move to the branding repo.
The branding repo already has this variable, can se use it? https://github.com/reustleco/dojo-admin-brand/blob/d2b2db36c76bdaa6e6d4a9327d602247441f3ae2/paragon/_variables.scss#L12

2022-08-24 06:32 UTC, bartosz-szczecinski-gft commented
Looks ok, the only thing I'd like to check before merging is the comment in `src/index.scss` - https://github.com/reustleco/dojo-frontend-app-learner-portal/pull/30#discussion_r953398091

2022-08-24 07:18 UTC, darjanin commented on src/components/dashboard/Dashboard.jsx
> +  const renderAvailableCourses = useCallback((count) => (
Yeah, this uses `useCallback` as yesterday I had on the dashboard the favorites sections shown that used this function and `count` of courses was different for it.

I'm going to remove this whole variable and just use the content of the function in the returned _render_ below. If we return the favorite section, it can be extracted to this callback when needed.

2022-08-24 07:23 UTC, darjanin commented on src/index.scss
> +// TODO: Move to the branding repo.
Thanks for pointing it's there. This variables wheren't loaded on the `learner-portal`, so they didn't overwrite the _paragon_'s defaults. I'll import the `dojo-admin-brand` variables into this project's SCSS.

2022-08-24 07:43 UTC, bartosz-szczecinski-gft approved these changes

2022-08-24 07:46 UTC, bartosz-szczecinski-gft commented on src/index.scss
> +@import "@reustleco/dojo-admin-brand/paragon/fonts";
@Alain1405 can you please confirm this is the proper way to inject the brand? This will give us access to the variables, but I'm just wondering how the brand is currently being overwritten by other ones than `dojo-admin-brand` (e.g. when are the other brands injected in the build pipeline)

2022-08-24 19:54 UTC, bartosz-szczecinski-gft commented
@darjanin we updated `dojo-admin-brand` to 1.0.17 (https://github.com/reustleco/dojo-admin-brand/compare/v1.0.15...v1.0.17) - please see if all the variables you needed are there and we can proceed with the update + merge

2022-08-25 02:30 UTC, Alain1405 commented on src/index.scss
> +@import "@reustleco/dojo-admin-brand/paragon/fonts";
@bartosz-szczecinski-gft I am not sure what you mean with `when are the other brands injected in the build pipeline`.
To my knowledge, the rules are those of CSS/SASS. Rules are applied sequentially so rules imported later in the code will dominate. New variables override older ones as well.
Have a look at the `dojo-frontend-admin` in order to see how we use the brand on a repo we wrote from scratch:
https://github.com/reustleco/dojo-frontend-admin/search?q=dojo-admin-brand

2022-08-25 02:30 UTC, Alain1405 approved these changes

2022-08-25 02:31 UTC, merged