[DP-313] Integrate the details component into learner app
reustleco/dojo-frontend-app-learner-portal pull request #37
Opened 2022-09-01 07:09 UTC by tetianabrzezinska

https://woven-dojo.atlassian.net/browse/DP-313

## Preview

![Screenshot 2022-09-01 at 09 07 56](https://user-images.githubusercontent.com/110455841/187853318-dd2db67b-9f52-452e-85f4-1f13d9ec9af2.png)

## Changes

The details component is integrated into learner app

## PR checks

* [ ] Did you add a preview image?
* [ ] Have you included the task ID in the PR title? (Format: `[ABC-###] - PR title`)
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Does your submission pass them?
* [ ] Have you lint your code locally prior to submission?
* [ ] Have you added an explanation of what your changes do?

2022-09-01 07:22 UTC, bartosz-szczecinski-gft requested changes
Not yet checked the CSS; we will probably create a ShadowContainer in the frontend-components repo, so some of the code would be moved.

2022-09-01 07:22 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +  const [activeCourse, setActiveCourse] = useState({});
You can have the initial state as `undefined`, which would allow us not to use `isEmpty` etc.

2022-09-01 07:22 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +  const onClick = (chosenCourse) => setActiveCourse(chosenCourse);
Please use a mroe descriptive name, e.g. `onCourseSelect`. Also typo `onDraweClose` -> `onDrawerClose`

2022-09-01 07:22 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +                  onClick: () => window.open(activeCourse.course_link, '_blank'),
According to @alain-scialoja-wp  comment (https://woven-dojo.atlassian.net/browse/DP-312?focusedCommentId=12150) we should be able to differentiate between external and dojo hosted courses. We can keep the label the same for now (https://www.figma.com/file/1cj98mfmjfwbxL8amfDf8P?node-id=1058:7132#250763543) but the behaviour should be different.

Not sure if this is currently properly handled by BE, because on my account I see some courses that have neither edx_course_id nor course_link

2022-09-01 07:25 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +  const onClick = (chosenCourse) => setActiveCourse(chosenCourse);
Also this helper doesn't really offer much benefit, can just use setActiveCourse directly on the Card components :)

2022-09-01 07:27 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +        <DashboardDrawer open={!(_isEmpty(activeCourse))} onClose={onDraweClose}>
We should consider (ask Manu please) if clicking outside of the component should also trigger the close event (e.g. with something like https://usehooks.com/useOnClickOutside/ or https://www.npmjs.com/package/react-onclickoutside)

2022-09-01 07:28 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +              ]}
We can use something like: 

```suggestion
              ].filter(item => !!item.value)}
```

to prevent displaying of items with no value returned from BE.

2022-09-01 08:20 UTC, tetianabrzezinska commented on src/components/dashboard/Dashboard.jsx
> +        <DashboardDrawer open={!(_isEmpty(activeCourse))} onClose={onDraweClose}>
Asked, it should close it. It works like that now

2022-09-01 08:21 UTC, Alain1405 reviewed
I know it's still in draft, but I have noticed that package-lock has changes (common was upgraded) but the changes are not reflected on package.json

2022-09-01 08:22 UTC, bartosz-szczecinski-gft commented
> I know it's still in draft, but I have noticed that package-lock has changes (common was upgraded) but the changes are not reflected on package.json

Looks OK for me, maybe you've marked the file as viewed?

![image](https://user-images.githubusercontent.com/90377295/187867709-48d3dfe8-1b27-47f1-b7d8-0f3faa8fbba0.png)

2022-09-01 08:24 UTC, Alain1405 commented
> > I know it's still in draft, but I have noticed that package-lock has changes (common was upgraded) but the changes are not reflected on package.json
> 
> Looks OK for me, maybe you've marked the file as viewed?
> 
> ![image](https://user-images.githubusercontent.com/90377295/187867709-48d3dfe8-1b27-47f1-b7d8-0f3faa8fbba0.png)

The version on package-lock is `1.1.7`.

2022-09-01 08:28 UTC, bartosz-szczecinski-gft commented
> The version on package-lock is `1.1.7`.

That's weird, because we're only up to 1.1.6

https://github.com/reustleco/dojo-frontend-common/releases

Also, the difference between package.json and package-lock.json would be because we're using `^` for versioning, which would silently update to the latest minor when doing `npm i`. We should change to use locked versions in package.json

2022-09-01 08:31 UTC, Alain1405 commented on src/components/dashboard/Dashboard.jsx
> +                  onClick: () => window.open(activeCourse.course_link, '_blank'),
You should see the Dojo Codelab demo now with `bartosz.szczecinski@gft.com`

2022-09-01 08:40 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +                  onClick: () => window.open(activeCourse.course_link, '_blank'),
> You should see the Dojo Codelab demo now with `bartosz.szczecinski@gft.com`

I'm not able to login with that email:

![image](https://user-images.githubusercontent.com/90377295/187870998-1e301235-c125-4e1f-ae5b-116143056a93.png)

I'm using the `bartosz.szczecinski+1@gft.com` one, and the results I get on that account have such courses:

![image](https://user-images.githubusercontent.com/90377295/187871212-b5a504b8-3dc5-4d4b-9e34-49853d27857a.png)

2022-09-01 08:42 UTC, Alain1405 commented on src/components/dashboard/Dashboard.jsx
> +                  onClick: () => window.open(activeCourse.course_link, '_blank'),
Try no with the +1 email. I will also re-invite with your original email.

2022-09-01 09:00 UTC, Alain1405 approved these changes

2022-09-01 09:02 UTC, bartosz-szczecinski-gft approved these changes

2022-09-01 09:06 UTC, merged

2022-09-02 06:54 UTC, bartosz-szczecinski-gft commented on src/components/dashboard/Dashboard.jsx
> +              description={activeCourse.full_description}
We're passing the full course description here, which can be HTLM content that ends up looking incorrect:

![image](https://user-images.githubusercontent.com/90377295/188076729-3003a123-b1fd-4763-876b-1ebe3d69d8f7.png)

We also have a `short_description` field, so maybe we should use that one instead?

![image](https://user-images.githubusercontent.com/90377295/188076804-dcd9f180-0fd3-4828-a7af-22512fc32e48.png)

CC @Alain1405  @tetianabrzezinska

2022-09-02 07:13 UTC, tetianabrzezinska commented on src/components/dashboard/Dashboard.jsx
> +              description={activeCourse.full_description}
I had such data, something was supposed to change
![Screenshot 2022-08-31 at 20 34 22](https://user-images.githubusercontent.com/110455841/188079811-4a5f820b-b278-4f0f-befa-40814be1f061.png)

2022-09-06 03:01 UTC, Alain1405 commented on src/components/dashboard/Dashboard.jsx
> +              description={activeCourse.full_description}
@bartosz-szczecinski-gft @tetianabrzezinska we don't need to support html. edX course do support it and thus when we import their metadata this occurs.
@OlhaShyliaieva do we have any way to handle this on the import function? (strip out html). That would be the easiest.  Manual cleanup would be a problem since the description field gets synced with the original periodically.
With [this](https://stackoverflow.com/a/14694669/1544643) for instance

2022-09-06 04:04 UTC, OlhaShyliaieva commented on src/components/dashboard/Dashboard.jsx
> +              description={activeCourse.full_description}
@Alain1405 Fixed it in the https://github.com/reustleco/dojo-enterprise-catalog-api/pull/24